//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2
use serde::Serialize;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "ymusic")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ymusic_id: String,
    pub ymusic_title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
